using System.Collections.Concurrent;
using System.Diagnostics;
using Microsoft.Extensions.Logging;
using DagNode.NDF.Interoperability.Model;
using DagNode.NDF.Interoperability.Model.Bash;

namespace DagNode.NDF.Interoperability.Bash;

public class FunctionProcessor : IDisposable, IAsyncDisposable
{
	private bool _disposed;

	public ParallelProcessType ParallelOptions { get => ParallelProcessType.SubprocessPerFunctionCall; }
	public BashProcess GetBashProcess()
	{
		switch (ParallelOptions) {
			case ParallelProcessType.SubprocessPerFunctionCall: return _pool.First();
			default: throw new NotImplementedException(ParallelOptions.ToString());
		}
	}

	private readonly ConcurrentQueue<BashProcess> _pool = new();
	
	private readonly ConcurrentQueue<FunctionStartEventArgs> _queueFunctionsToCall = new();
	private readonly ConcurrentDictionary<string, FunctionStartEventArgs> _queueRunningFunctions = new();
	private readonly ConcurrentDictionary<long, IFunctionResultMetadata> _queueFinishedFunctions = new();
	// Marker tag -> the backgrounded call's root PID, reported by ___BEGIN_FN__. Lock-free; the hot path
	// (dispatch, result) touches only concurrent collections. Read on the rare termination path.
	private readonly ConcurrentDictionary<string, int> _runningCallPids = new();

	#region Interlocked properties

	public bool IsCallingFunctions { get => _IsCallingFunctions; }
	private bool _IsCallingFunctions {
		get => Interlocked.CompareExchange(ref _isCallingFunctions, 0, 0) == 1;
		set => Interlocked.Exchange(ref _isCallingFunctions, value ? 1 : 0);
	}
	private int _isCallingFunctions;
	private readonly SemaphoreSlim _isCallingFunctionsLock = new(1, 1);

	#endregion Interlocked properties

	private readonly ILogger _logger;
	private readonly CancellationTokenSource _cts;
	private readonly BashScript _bashScript;

	public FunctionProcessor(BashScript bashScript, ILogger logger, CancellationTokenSource cts)
	{
		_logger = logger ?? throw new ArgumentException(nameof(logger));
		_cts = cts ?? throw new ArgumentException(nameof(cts));
		_bashScript = bashScript;
		
		switch (ParallelOptions) {
			case ParallelProcessType.SubprocessPerFunctionCall:
				BashProcess mainBashProcess = CreateBashProcess(logger, bashScript.BashProcessSettings);
				_pool.Enqueue(mainBashProcess);
				break;
			default: throw new NotImplementedException(ParallelOptions.ToString());
		}
	}

	private BashProcess CreateBashProcess(ILogger logger, BashProcessSettings bashProcessSettings)
	{
		BashProcess bashProcess = new (logger, bashProcessSettings);
		// Register handlers
		bashProcess.EventHandlerFunctionResultReadyAsync += ProcessResult;
		bashProcess.EventHandlerErrorStreamReceivedAsync += HandleError;
		bashProcess.EventHandlerFunctionPidReadyAsync += RecordFunctionPid;
		return bashProcess;
	}

	/// <summary>
	/// A method to process files (results) generated by the function.
	/// Triggered by catching function end marker in bash process standard output stream.
	/// Standard output stream from the function is redirected to one the result files,
	/// not to the standard output stream of the process.
	/// </summary>
	/// <param name="sender">Bash process which received function end marker.</param>
	/// <param name="args">Metadata from the function end marker.</param>
	/// <exception cref="InteroperabilityException"></exception>
	private async Task ProcessResult(BashProcess sender, FunctionResultReadyEventArgs args)
	{
		IFunctionResultMetadata metadata = args.Metadata;
		try {
			// Get/Remove FunctionStartEventArgs from the running functions queue 
			FunctionStartEventArgs startArgs = PopRunningFunctionItemThreadSafe(metadata.FunctionMarkerTag);
			CallOptions callOptions = startArgs.CallOptions; // Call options from start args

			// Read function results from locations specified in call options
			string? inputIn, standardOutput, standardError, customLog, customFile = null;
			standardOutput = callOptions.HasOutFile() ? await Helpers.ReadFileContentsAsync(startArgs.OutFilePath).ConfigureAwait(false) : null;
			standardError = callOptions.HasErrFile() ? await Helpers.ReadFileContentsAsync(startArgs.ErrFilePath).ConfigureAwait(false) : null;
			customLog = callOptions.HasLogFile() ? await Helpers.ReadFileContentsAsync(startArgs.LogFilePath).ConfigureAwait(false) : null;
			inputIn = callOptions.HasInFile() ? await Helpers.ReadFileContentsAsync(startArgs.InFilePath).ConfigureAwait(false) : null;
			if (callOptions.ReadResultFrom.LocationType == ResultLocationType.CustomPath) {
				customFile = await Helpers.ReadFileContentsAsync(callOptions.ReadResultFrom.CustomPath!).ConfigureAwait(false);
			}
			var functionResult = new FunctionResult(metadata.ExitCode, inputIn, standardOutput, standardError, customLog, customFile);
			
			// TrySetResult, not SetResult: the caller may have cancelled its wait (RunFunctionAsync
			// links the per-call token onto this source), leaving it already completed. The function
			// still ran, so record the result for the trace and drop it for the caller.
			startArgs.FunctionResultCompletionSource.TrySetResult(functionResult);
			_runningCallPids.TryRemove(metadata.FunctionMarkerTag, out _); // Finished: drop its PID
			TrackFinishedItemThreadSafe(startArgs, metadata);
		} catch (Exception ex) {
			throw new InteroperabilityException(ex, $"Error processing result for {metadata.FunctionMarkerTag}");
		}
	}

	/// <summary>
	/// A method to handle unexpected errors from bash process standard error stream.
	/// Normally, there should not be any messages published. Function std err is redirected to file by default,
	/// not to this standard error stream.
	/// </summary>
	/// <param name="sender">Bash process which received message on std err.</param>
	/// <param name="args">Error message</param>
	/// <exception cref="InteroperabilityException"></exception>
	private async Task HandleError(BashProcess sender, ErrorStreamReceivedEventArgs args)
	{
		string line = args.Error;
		string syslogMessage = line.ToSyslogMessage(sender.Process.Id, "[ERR]");
		_logger.LogError("{SyslogMessage}", syslogMessage.ToLogLine());
		if (_bashScript.BashProcessSettings.TerminateOnErrorStreamReceived) {
			_bashScript.Dispose();
		}
	}
	
	/// <summary>
	/// Records a call's root PID from its <c>___BEGIN_FN__</c> marker, but only while the call is still
	/// running: a marker that races behind a very fast call's <c>___END_FN__</c> is dropped so the
	/// registry does not leak a PID whose call already finished.
	/// </summary>
	private Task RecordFunctionPid(BashProcess sender, FunctionPidReadyEventArgs args)
	{
		if (_queueRunningFunctions.ContainsKey(args.FunctionMarkerTag)) {
			_runningCallPids[args.FunctionMarkerTag] = args.Pid;
		}
		return Task.CompletedTask;
	}

	/// <summary>
	/// Terminates one call's process tree (SIGTERM, <paramref name="gracePeriod"/>, SIGKILL) when its
	/// wait ends early. The root PID comes from the in-memory registry, falling back to the tmpfs pid
	/// file when <c>___BEGIN_FN__</c> has not been parsed yet. An unknown or already-removed PID (the
	/// call finished) is a no-op.
	/// </summary>
	public async Task TerminateCallAsync(string functionMarkerTag, TimeSpan gracePeriod, CancellationToken cancellationToken = default)
	{
		int? rootPid = ResolveCallPid(functionMarkerTag);
		if (rootPid is null) return;
		try {
			await ProcessTree.TerminateTreeAsync(rootPid.Value, gracePeriod, cancellationToken).ConfigureAwait(false);
		} finally {
			_runningCallPids.TryRemove(functionMarkerTag, out _);
		}
	}

	private int? ResolveCallPid(string functionMarkerTag)
	{
		if (_runningCallPids.TryGetValue(functionMarkerTag, out int pid)) return pid;
		// Fallback: the pid file on tmpfs. Absent means the call already finished (the subshell removes
		// it on completion), so there is nothing to terminate.
		string pidFilePath = Path.Combine(FunctionWorkDirSettings.FunctionBasePidDir, $"{functionMarkerTag}.pid");
		try {
			return File.Exists(pidFilePath) && int.TryParse(File.ReadAllText(pidFilePath).Trim(), out int filePid)
				? filePid : (int?)null;
		} catch (Exception) {
			return null;
		}
	}

	internal async Task StartAsync(CancellationToken cancellationToken = default)
	{
		// Link the caller's startup token with the instance lifetime so either ends startup, then hand
		// the linked source to the CTS-based plumbing (mount, sourcing) below.
		using var linkedCts = CancellationTokenSource.CreateLinkedTokenSource(_cts.Token, cancellationToken);
		await _isCallingFunctionsLock.WaitAsync(linkedCts.Token).ConfigureAwait(false);
		try {
			if (_IsCallingFunctions) return;
			_IsCallingFunctions = true;
		} finally {
			_isCallingFunctionsLock.Release();
		}

		// Mount in-memory temporary filesystem
		await LinuxUtils.MountTmpfsBsAsync(_logger, linkedCts).ConfigureAwait(false);

		// Source all script files to become available for all bash processes from the pool
		await SourceScriptFilesAsync(cancellationToken).ConfigureAwait(false);

		try {
			// Main loop, non-blocking
			var runFunctions = Task.Run(async () => {
				await RunEnqueuedFunctionCallsAsync().ConfigureAwait(false);
			}, _cts.Token).ConfigureAwait(false);
		} catch (Exception ex) {
			throw new InteroperabilityException(ex, "Error running functions");
		}
	}

	private async Task RunEnqueuedFunctionCallsAsync()
	{
		// Run indefinitely
		while (!_cts.IsCancellationRequested) {
			// Check enqueued function calls every 10 milliseconds
			if (!_queueFunctionsToCall.TryDequeue(out FunctionStartEventArgs startArgs)) {
				await Task.Delay(TimeSpan.FromMilliseconds(10), _cts.Token).ConfigureAwait(false);
				continue;
			}
			// Keep track of running functions, we will need function start args to process result from correct outputs
			PushRunningFunctionItemThreadSafe(startArgs);
			string bashFunctionArgs = startArgs.FunctionQuery.Compile();
			// Carries caller-supplied function args, so escape it like any other untrusted text.
			if (_bashScript.IsDebug) _logger.LogDebug("FunctionQuery: {FunctionQuery}", bashFunctionArgs.ToLogLine());
			// Send function call to the Bash process
			Process currentProcess = GetBashProcess().Process;
			await currentProcess.StandardInput.WriteLineAsync(bashFunctionArgs).ConfigureAwait(false);
			await currentProcess.StandardInput.FlushAsync().ConfigureAwait(false);
		}
	}

	public string PrintFunctionCallTrace() =>
		string.Join(Environment.NewLine,
			_queueFinishedFunctions.OrderByDescending(x => x.Key)
				.Select(kv => $"{kv.Key}.: {kv.Value.ExitCode} at {kv.Value.FunctionEndTimeUtc:yyyyMMdd HH:mm:ss-fff} from {kv.Value.FunctionMarkerTag} in {kv.Value.Duration.ToReadable()}"));

	public async Task<bool> SourceScriptFilesAsync(CancellationToken cancellationToken = default)
	{
		try {
			// The BashProcess.Source* methods take a CTS (they cancel it on error); link the caller's
			// token with the instance lifetime and pass the linked source down.
			using var linkedCts = CancellationTokenSource.CreateLinkedTokenSource(_cts.Token, cancellationToken);
			// Initialize all bash processes from the pool
			foreach (BashProcess bashProcess in _pool) {
				// Source main function call wrapper function
				await bashProcess.SourceMainFunctionWrapperAsync(linkedCts).ConfigureAwait(false);
				// Additionally source all user-provided global function scripts
				await bashProcess.SourceGlobalFunctionsAsync(_bashScript.BashScriptSettings.GlobalFunctionScriptFilePaths, linkedCts).ConfigureAwait(false);
				// Source bash script
				await bashProcess.SourceScriptFileAsync(_bashScript.ScriptFilePath, linkedCts).ConfigureAwait(false);
			}

			return true;
		} catch (Exception ex) {
			throw new InteroperabilityException(ex, "Error sourcing script files");
		}
	}
	
	#region Concurrent queue methods
	public void EnqueueCallFunctionItemThreadSafe(FunctionStartEventArgs functionStartEventArgs)
	{
		_queueFunctionsToCall.Enqueue(functionStartEventArgs);
	}
	public void PushRunningFunctionItemThreadSafe(FunctionStartEventArgs startArgs)
	{
		_queueRunningFunctions.AddOrUpdate(startArgs.FunctionMarkerTag, startArgs, (k, v) => startArgs);
	}
	public FunctionStartEventArgs PopRunningFunctionItemThreadSafe(string functionMarkerTag)
	{
		_queueRunningFunctions.TryRemove(functionMarkerTag, out FunctionStartEventArgs startArgs);
		return startArgs;
	}
	public void TrackFinishedItemThreadSafe(FunctionStartEventArgs startArgs, IFunctionResultMetadata metadata)
	{
		_queueFinishedFunctions.TryAdd(startArgs.SequenceNumber, metadata);
	}
	
	#endregion Concurrent queue method
	#region Types
	
	public enum ParallelProcessType
	{
		Default,

		/// <summary>
		/// The main bash process spawns subprocesses (system background tasks)
		/// for every function call (fifo/pid &amp;).
		/// UseCase: Running many asynchronous functions.
		/// </summary>
		SubprocessPerFunctionCall,

		/// <summary>
		/// A pool with fixed number of bash processes (ideally up to max number of CPU cores).
		/// Bash processes do not spawn subprocesses per function call (system background tasks),
		/// but run functions synchronously (pool/fifo/pid, no &amp;).
		/// UseCase: CPU-bound function workloads.
		/// </summary>
		FixedPool,

		/// <summary>
		/// A special case of FixedPool with single bash process.
		/// UseCase: Good for debugging, execute functions synchronously one after each other.
		/// </summary>
		SingleProcess,
	}
	
	#endregion Types
	
	/// <summary>
	/// Graceful shutdown: waits for calls already queued or running to finish, bounded by
	/// <see cref="BashScriptSettings.DisposeDrainTimeout"/>, then stops the bash processes.
	/// </summary>
	public async ValueTask DisposeAsync()
	{
		if (_disposed) return;
		await DrainInFlightCallsAsync(_bashScript.BashScriptSettings.DisposeDrainTimeout).ConfigureAwait(false);
		Dispose();
	}

	/// <summary>
	/// Awaits the completion sources of every queued or running call so a caller disposing
	/// asynchronously sees them finish. The dispatch loop and result readers run on the instance
	/// lifetime token, which the caller cancels only after this returns, so the calls can still
	/// complete. Bounded by <paramref name="drainTimeout"/>: <see cref="Timeout.InfiniteTimeSpan"/>
	/// waits without a cap, <see cref="TimeSpan.Zero"/> returns immediately.
	/// </summary>
	private async Task DrainInFlightCallsAsync(TimeSpan drainTimeout)
	{
		if (drainTimeout == TimeSpan.Zero) return;
		var pending = _queueFunctionsToCall.Select(x => x.FunctionResultCompletionSource.Task)
			.Concat(_queueRunningFunctions.Values.Select(x => x.FunctionResultCompletionSource.Task))
			.ToArray();
		if (pending.Length == 0) return;
		var drain = Task.WhenAll(pending);
		if (drainTimeout == Timeout.InfiniteTimeSpan) {
			await SwallowAsync(drain).ConfigureAwait(false);
			return;
		}
		using var timeoutCts = new CancellationTokenSource(drainTimeout);
		// Whichever finishes first: every call completing, or the drain budget elapsing.
		await SwallowAsync(Task.WhenAny(drain, Task.Delay(Timeout.Infinite, timeoutCts.Token))).ConfigureAwait(false);
		if (drain.IsCompleted) await SwallowAsync(drain).ConfigureAwait(false); // Observe faults/cancellations
	}

	// A call that cancelled or faulted while draining is not a shutdown failure, so its exception is
	// observed and dropped rather than propagated out of DisposeAsync.
	private static async Task SwallowAsync(Task task)
	{
		try {
			await task.ConfigureAwait(false);
		} catch {
			// Intentionally ignored during shutdown.
		}
	}

	public void Dispose()
	{
		if (_disposed) return;
		_disposed = true;
		foreach (BashProcess bashProcess in _pool) {
			bashProcess.EventHandlerFunctionResultReadyAsync -= ProcessResult;
			bashProcess.EventHandlerErrorStreamReceivedAsync -= HandleError;
			bashProcess.EventHandlerFunctionPidReadyAsync -= RecordFunctionPid;
			bashProcess.Dispose();
		}
	}
}
